### ISSUE TITLE
Roll package

### ISSUE THREAD

**Issue by arnaldorusso** [Zulko/unroll#2]
Hi Zulko,

I was imagining here a function that could generate printable music box rolls from midi or from .ly files.
What do you think about it?
If you think this interesting I could contribute to.

Cheers,
Arnaldo.

**Comment by Zulko** [comment]
I don't know... This is really different from what the package is for and I can't see any function in Unroll that could help you in this project. From midi files, it should be easy to do, but from lilypond sources, this looks complicated. In these conditions maybe it is better to start your own project (I'll follow it :) )

**Comment by arnaldorusso** [comment]
I'll try in the near future and I'll say! Thank's for your feedback!
